### ISSUE TITLE
Script to assign percentile rank for individual articles

### ISSUE THREAD

**Issue by michaelbales1** [wcmc-its/vivodashboard#6]

**Comment by pra2008** [comment]
How do I get category for a given article? Can't locate a table that specifies category for an article. This is essential in order to calculate the percentile ranking for an individual article.

**Comment by pra2008** [comment]
How do I get article type ( journal article or review) for a given article? Search index has a table called search_api_db_publications_publication_types. Can't locate a field_data_field_* table for article type.

**Comment by michaelbales1** [comment]
Hi Prakash, does this question relate to the database that VIVO dashboard uses?

**Comment by pra2008** [comment]
Michael, I'm referring to VIVO dashboard database. Paul might have some suggestions how to get category as well as article type for an article in vivodashboard.

**Comment by paulalbert1** [comment]
This is handled by the taxonomy module, I think. Find the ID in field_data_field_rdf_type.field_rdf.type_tid and look it up in taxonomy_term_data.tid. Does that make sense?

**Comment by pra2008** [comment]
This is I was able to get Journal Name for an article. For article type, it is not that evident, though. I think the delta value has something to to do in finding the article type.

**Comment by pra2008** [comment]
For article types, tid values of 9 and 71 seems to be working for Academic Article and Review. 
However, for article category, no tid value seems to be matching.  If we query taxonomy_term_date table for rdf type ( which is vid = 6),  the result set contains other rdf types, but no article category.  Also what would be the logic to identity is_first_last_author for an article?

**Comment by milesw** [comment]
Hi guys, I'm not sure where you're doing your querying, but if you're working in PHP it might be useful to bootstrap Drupal so you can use all its built-in object loading, such as taxonomy_term_load().

```php
<?php
// Set the working directory to your Drupal root
define('DRUPAL_ROOT', '/path/to/drupal');
require_once DRUPAL_ROOT . '/includes/bootstrap.inc';

// Load Drupal
// If you are not running the script through a web server, it may be necessary to set server variables yourself. It is also important to set HTTP_HOST if you are using multi-site.
$_SERVER['HTTP_HOST'] = 'www.example.com:8888';
$_SERVER['REMOTE_ADDR'] = '127.0.0.1';
$_SERVER['REQUEST_METHOD'] = 'GET';
$_SERVER['SCRIPT_NAME'] = '/' . basename(__FILE__);
drupal_bootstrap(DRUPAL_BOOTSTRAP_FULL);
// You don't have to do a full bootstrap. Check the API for all the different phases you can use.

// Drupal is now fully bootstrapped. You have full access to the API.
// ...add your code here.
$term = taxonomy_term_load(9);
?>
```

From: http://david.narrabilis.com/node/39

**Comment by pra2008** [comment]
Hi Miles,
Thanks so much for sending out this note. This is Prakash from WCMC, currently working with Paul and Michael to implement a citation impact chart for articles authored by WCMC faculty on our VIVO Dashbaord: http://dev-vivo-dashboard.gotpantheon.com<http://dev-vivo-dashboard.gotpantheon.com/>

I'm having hard time to construct a query that would fetch all authors with an id (CWID) and their corresponding publications with all the taxonomy terms associated with both author and publication.  Is this something I can construct through EntityFieldQuery in Drupal?  In other words, how do I select all publications and their authors from various tables in vivo dashboard database?

Eventually, I need to populate a table something like the following:
pmid, pubtype,  citation_count, percentile_rank, cover_date, category, is_first_or_last_author, title, publication_name, pages, volume, issue, nlmabbreviation, scopus_doc_id, authors
15306676,Journal Article,8,45,8/1/2012,PHARMACOLOGY & PHARMACY,1,Intensive versus moderate lipid lowering with statins after acute coronary syndromes [2] (multiple letters),New England Journal of Medicine,1027-8,97,11,,3943068471,Herd JA|West MS|Ballantyne C|Farmer J|Gotto AM

Note that percentile_rank is something I can calculate using a set of baseline publications from Pubmed.  Rest of the fields, I need to fetch from various tables in vivo dashboard.

I'm doing all queris from within a custom module in VIVO Dashboard.
You did a fantastic job implementing the publications chart in VIVO Dashboard.  I would greatly appreciate, if you could give me some directions here.

--
Regards,
Prakash Adekkanattu

**Comment by milesw** [comment]
Hi Prakash,

Yes, the Drupal db structure is not so straightforward. It's expected that you'll use either entity loading, the database API, or the Views module, which all abstract away the table structure.

EntityFieldQuery is useful if you need a simple list of entities (like author nodes), allowing you to easily add field conditions to the query. But it's not intended for complex queries with custom joins. To populate a custom table you're probably best off building queries with db_select(). 

However, if you will need to implement facets along with your graph, you will be much better off storing/querying data via Search API. From the example you gave, the basic data you need is authorship data. There is already a Search API index called Authorships, so it might just be a matter or indexing some additional fields (/admin/config/search/search_api/index/authorships/fields). 

Data for the publication graph works like this:

1. Publication nodes get created/updated
2. Search API indexes data into the Publications index
3. During indexing, Facet API stores data it needs for facets

Display of the publication graph works like this:

1. The Views module builds a Search API query on the Publications index
2. Facet API adds additional queries for facet data
3. Views renders the publication results
4. Facet API renders facet data as graph (FacetAPI Graphs module)

Your graph might be too complex to be implemented as a facet. But what you can do is use Views to create a view, just like the data export views which use Authorships index, then call views_get_view_result() in your custom module to get the raw results and format the graph.

**Comment by pra2008** [comment]
Hi Miles,
Thanks so much of the detailed guidelines. I did manage to query authorships through db_select().
I do agree that Search API is probably the best way to implement facets, and I'm planning to go with that route.
For citation count charts, we are implementing facets for author name, publication types, first/last author and categories.
I will let you know, how that goes.

--
Regards,
Prakash Adekkanattu

**Comment by pra2008** [comment]
Hi Miles,
Hope you are doing fine. Thanks for all the directions earlier.  Following some of you suggestions, I was able to implement the citations impact data visualization on vivodashboard.
http://live-vivo-dashboard.gotpantheon.com<http://live-vivo-dashboard.gotpantheon.com/citations/main>

A couple of issues I still need to sort out. I was hoping you could give me some advise how to address these issues.
For some reason the publication import has stopped importing new publications from our vivo instance. The import script on Cron is running, though.  I see the following error message in  Feeds log file:
[cid:974F8E16-0889-4915-B414-0F90A4F7B0E5]


I'm not sure, what these error messages mean.  How can I address this?

A second issue, I'm facing is performance.  Load time is quite substantial for citation impact pages to load.
The citation impact graph works some what similar to the way you implemented the publication graph:

  1.  The Views module builds a Search API query on the Citation index
  2.  Facet API adds additional queries for facet data
  3.  Views renders the citations results
  4.  Receive view  in a custom module,  get the raw results and format the graph by making additional queries to some of the tables.
  5.  Data visualization is through D3 library.

Citations view contains quite a large number of publications, and step 4 normally takes significant time to process the raw data to be suitable for D3 visualization.
Do you have any suggestions that would improve the overall page load time?

Much appreciated.
--
Regards,
Prakash Adekkanattu
